# -*- coding: utf-8 -*-
"""ScrapingPlayStorePLNMObile.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p-46UYx5C-btu5oS4I4An0fiuWiKmlit
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Commented out IPython magic to ensure Python compatibility.
# %pip install tqdm

from tqdm import tqdm
tqdm.pandas()  # Integrasi tqdm dengan pandas

!pip install google-play-scraper

import pandas as pd
import numpy as np
from google_play_scraper import app, reviews
import os
import nltk
from nltk.corpus import stopwords
from nltk.sentiment import SentimentIntensityAnalyzer
from google_play_scraper import app, Sort, reviews_all

app_id = 'com.icon.pln123'
# Mengambil ulasan
reviews_data, _ = reviews(
    app_id,
    lang='id',
    country='id',
    count=10000
)

# Konversi ke DataFrame
reviews_df = pd.DataFrame(reviews_data)
reviews_df

# save to csv
reviews_df.to_csv('hasil_reviews_pln_mobile.csv', index=False)